CREATE TABLE IF NOT EXISTS characters(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    image text NOT NULL,
    name text NOT NULL,
    age integer NOT NULL,
    story text NOT NULL,
    moviesid INTEGER REFERENCES movies(id)
)

CREATE TABLE IF NOT EXISTS movies(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    image text NOT NULL,
    title text NOT NULL,
    date date NOT NULL,
    rating integer NOT NULL,
    charactersId INTEGER REFERENCES characters(id)
);

CREATE TABLE IF NOT EXISTS users(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,    
    username text NOT NULL,
    email text NOT NULL,
    password text NOT NULL
);

INSERT INTO characters( image, name, age, story, moviesid)
    VALUES( 'url', 'Lilo Pelekai', 5, 'She is a young Native Hawaiian girl who lives on the island of Kauaʻi with her older sister Nani and her extended family of alien visitors marooned on Earth.', 1);

INSERT INTO characters( image, name, age, story, moviesid)
    VALUES('url', 'James P. Sullivan', 28, 'He is a large mammalian monster with shaggy aqua fur with purple blotches, two small horns on his head, and a long tail.', 2);

INSERT INTO characters(image, name, age, story, moviesid)
    VALUES( 'url', 'Dory', 5, 'Dory is very optimistic and kind but a ditzy and forgetful fish. This is because she suffers from short-term memory loss.', 3);
 
INSERT INTO movies( image, title, date, rating, charactersid)
    VALUES('url', 'Lilo and Stitch', 'June 14, 2002', 4, 1);

INSERT INTO movies( image, title, date, rating, charactersid)
    VALUES('url', 'Monsters, INC.', 'October 28, 2001', 4, 2);

INSERT INTO movies( image, title, date, rating, charactersid)
    VALUES('url', 'Finding Nemo', 'May 30, 2003', 5, 3);